version: '3'
services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/src
    depends_on:
      - migration
    environment:
      - DB_HOST=db
      - DB_USER=gino
    command: /env/bin/uvicorn --host 0.0.0.0 --port 80 gino_fastapi_demo.asgi:app --reload
  migration:
    build: .
    volumes:
      - .:/src
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=gino
    command: /env/bin/alembic upgrade head
  db:
    image: postgres
    environment:
      - POSTGRES_USER=gino
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
